spring:
  application:
    name: cloud-server
  security:
    user:
      name: joe
      password: hadoop

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    #显示真实ip地址
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: false
    fetch-registry: false
    client:
      service-url:
        defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer2:8762/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@peer3:8763/eureka/
    management:
      endpoints:
        web:
          exposure:
            include: "*"
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    wait-time-in-ms-when-sync-empty: 0