spring:
  cloud:
    config:
      name: cloud-consumer
      uri: http://localhost:8888
      label: master
  application:
    name: cloud-consumer

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://joe:hadoop@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream
  endpoint:
    health:
      show-details: always