spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
#          uri: http://gitlab.dicyun.win:10080/java-training/cloud_manage_lyx.git
          username: JoeAnimation
          password: lyx484520
          search-paths: config-repo
          basedir: F:\\java-training\\localGitRepo\\
          uri: 
      label: master
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://joe:hadoop@localhost:8761/eureka/